---
url: http://rubyspec.org
safe: true
lsi: false
permalink: pretty
source: .
destination: ./public
exclude:
  - Rakefile
  - README.md
  - Gemfile
  - Gemfile.lock
  - CNAME
  - .gitignore
  - ./public
  - ./stylesheets/*.scss
markdown: rdiscount
pygments: true
pygments: false
port: 9876
